### ISSUE TITLE
CR123a

### ISSUE THREAD

**Issue by bpbastos** [ghmartin77/ESP8266_BME280#2]
Hello @ghmartin77 

It's not really an issue, but I'd like to know if you have any info about how long it last on cr123a battery.

Thanks

**Comment by ghmartin77** [comment]
Hi @bpbastos, 

Depends on several things like temperature changes, configuration parameters, Wifi connectivity, battery make. For my typical environment it's about 6 months.

Here's a graph of VCC of the last year. You can see the first battery was replaced in Jan'20 after powering the device from Jul'19 to Dec'20.

![grafik](https://user-images.githubusercontent.com/25515110/83810464-78da7f00-a6b8-11ea-8b61-e92815864e5f.png)

Hope this helps.

Best regards,
ghmartin77

**Comment by bpbastos** [comment]
Thank you @ghmartin77 it'll help a lot! Do you mind share the update frequency?

Bests

**Comment by ghmartin77** [comment]
It's running with the configuration as preset in https://github.com/ghmartin77/ESP8266_BME280/blob/master/ESP8266_BME280/defines.h
