### ISSUE TITLE
Readme Request: More info on parts being removed.

### ISSUE THREAD

**Issue by ChrisWeiss** [ghmartin77/ESP8266_BME280#3]
Looks very slick, can you go into more detail on what the parts are you're removing and why (I get the LED, but what about the resistor and desoldering the pins on the chip?)

**Comment by ghmartin77** [comment]
Hi Chris,

(100K) Resistor is removed to make ESP.getVCC() work properly. For details see here: https://github.com/esp8266/Arduino/issues/721#issuecomment-296994054
The pins of the CH340C are removed to disable power supply for the (not needed) USB2UART chip. You can also remove the chip completely.
Wemos D1 mini schematics are available here for further reference: https://docs.wemos.cc/en/latest/_static/files/sch_d1_mini_v3.0.0.pdf

Best regards,
ghmartin77
